services:
  postgres:
    container_name: postgres-sql-gt
    image: postgres
    environment:
      POSTGRES_USER: banasiak
      POSTGRES_PASSWORD: banasiak
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gym_track
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring_demo
    restart: unless-stopped


  mail-dev:
    container_name: mail-dev-gt
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  gt-api:
    container_name: gt-api
    image: gt/gt-api:1.0.4
    ports:
      - 8088:8088
    networks:
      - spring_demo
    depends_on:
      - postgres
  gt-ui:
    container_name: gt-ui
    image: gt/gt-ui:1.0.5
    ports:
      - 8080:80
    networks:
      - spring_demo
    depends_on:
      - gt-api

networks:
  spring_demo:
    driver: bridge

volumes:
  postgres:
    driver: local