create table if not exists role
(
    id                 bigint generated by default as identity
        primary key,
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6),
    name               varchar(255)
        constraint uk8sewwnpamngi6b1dwaa88askk
            unique
);

alter table role
    owner to banasiak;

create table if not exists users
(
    id                 bigint generated by default as identity
        primary key,
    account_locked     boolean      not null,
    created_date       timestamp(6) not null,
    email              varchar(255)
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    enable             boolean      not null,
    last_modified_date timestamp(6),
    name               varchar(255),
    password           varchar(255)
);

alter table users
    owner to banasiak;

create table if not exists exercises
(
    id            bigint generated by default as identity
        primary key,
    created_by    bigint       not null,
    created_date  timestamp(6) not null,
    modified_by   bigint,
    modified_date timestamp(6),
    exercise_type smallint
        constraint exercises_exercise_type_check
            check ((exercise_type >= 0) AND (exercise_type <= 10)),
    is_default    boolean      not null,
    name          varchar(255),
    user_id       bigint
        constraint fkkiftckymv693t6yxogsb50n4y
            references users
);

alter table exercises
    owner to banasiak;

create table if not exists plans
(
    id            bigint generated by default as identity
        primary key,
    created_by    bigint       not null,
    created_date  timestamp(6) not null,
    modified_by   bigint,
    modified_date timestamp(6),
    name          varchar(255),
    user_id       bigint
        constraint fkbybv5po44ssyv6svnv062dwrf
            references users
);

alter table plans
    owner to banasiak;

create table if not exists "plan-exercise"
(
    id            bigint generated by default as identity
        primary key,
    created_by    bigint       not null,
    created_date  timestamp(6) not null,
    modified_by   bigint,
    modified_date timestamp(6),
    sets          integer,
    exercise_id   bigint       not null
        constraint fki5sserlnonuaoo2txi4fww38m
            references exercises,
    user_id       bigint       not null
        constraint fkj7v8yai901h6mn2ye7g00v6gy
            references users,
    plan_id       bigint
        constraint fk50p3ijycxmcfh6aub32yj2poe
            references plans
);

alter table "plan-exercise"
    owner to banasiak;

create table if not exists token
(
    id           bigint not null
        primary key,
    created_at   timestamp(6),
    expires_at   timestamp(6),
    token        varchar(255)
        constraint ukpddrhgwxnms2aceeku9s2ewy5
            unique,
    validated_at timestamp(6),
    user_id      bigint not null
        constraint fkj8rfw4x0wjjyibfqq566j4qng
            references users
);

alter table token
    owner to banasiak;

create table if not exists users_roles
(
    users_id bigint not null
        constraint fkml90kef4w2jy7oxyqv742tsfc
            references users,
    roles_id bigint not null
        constraint fk15d410tj6juko0sq9k4km60xq
            references role
);

alter table users_roles
    owner to banasiak;

create table if not exists weight
(
    id            bigint generated by default as identity
        primary key,
    created_by    bigint       not null,
    created_date  timestamp(6) not null,
    modified_by   bigint,
    modified_date timestamp(6),
    date          date,
    weight        double precision,
    user_id       bigint       not null
        constraint fkd70tg0kr1mby26ipikfhp1hjq
            references users
);

alter table weight
    owner to banasiak;

create table if not exists workout_session
(
    id              bigint generated by default as identity
        primary key,
    created_by      bigint       not null,
    created_date    timestamp(6) not null,
    modified_by     bigint,
    modified_date   timestamp(6),
    ended           boolean      not null,
    session_date    date,
    user_id         bigint       not null
        constraint fkcufeiyawnkbbkuj235rwsj03a
            references users,
    workout_plan_id bigint       not null
        constraint fknqu7kwppo0gk3h56o3s5lsbdd
            references plans
);

alter table workout_session
    owner to banasiak;

create table if not exists workout_logs
(
    id                 bigint generated by default as identity
        primary key,
    created_by         bigint       not null,
    created_date       timestamp(6) not null,
    modified_by        bigint,
    modified_date      timestamp(6),
    reps               integer,
    set_number         integer,
    summary_weight     double precision,
    weight             double precision,
    plan_exercise_id   bigint       not null
        constraint fkgqu6a2fwax5lt1fyfd9unac8s
            references "plan-exercise",
    workout_session_id bigint       not null
        constraint fkpb3l5pqwu07pb3k40a52mkxjj
            references workout_session
);

alter table workout_logs
    owner to banasiak;

create table if not exists notes
(
    id            bigint generated by default as identity
        primary key,
    created_by    bigint       not null,
    created_date  timestamp(6) not null,
    modified_by   bigint,
    modified_date timestamp(6),
    date          date,
    note          varchar(255),
    exercise_id   bigint       not null
        constraint fklq6jnudvag85f6e6d5iseyapn
            references exercises,
    user_id       bigint       not null
        constraint fkechaouoa6kus6k1dpix1u91c
            references users
);

alter table notes
    owner to banasiak;

