INSERT INTO users (account_locked, created_date, email, enable)
VALUES (true, CURRENT_TIMESTAMP, 'mockUser@example.xp', false);

INSERT INTO exercises (created_by, created_date, exercise_type, is_default, name, user_id) VALUES
   (1, CURRENT_TIMESTAMP, 0, true, 'Bench press barbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Bench press wide grip barbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Bench press dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Bench press cable', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Bench press machine', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Bench press smith', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Decline bench press barbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Decline bench press dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Decline bench press smith', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline bench press barbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline bench press dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline bench press smith', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline bench press machine', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Cable fly high', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Cable fly low', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Cable fly middle', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest dip', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest dip assisted', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest dip weighted', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest fly machine', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest fly dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest fly cable', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline chest fly machine', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline chest fly dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline chest fly cable', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Single arm chest fly', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Chest press machine', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Push ups', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Push ups close grip', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Decline push ups', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Incline push ups', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Push ups weighted', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Floor press dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Floor press barbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Hax press', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Plate press', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Pullover dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 0, true, 'Pullover machine', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Lateral raise cable', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Lateral raise machine', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Lateral raise dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Lateral raise band', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Single arm lateral raise cable', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Seated lateral raise', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Standing military press barbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Seated overhead press barbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Overhead press smith', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Standing shoulder press dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Seated shoulder press dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Shoulder press machine', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Arnold press', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Chest supported Y raise', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Face pull', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Push press', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Front raise barbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Front raise cable', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Front raise dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 1, true, 'Handstand push up', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Biceps curl barbell', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Biceps curl dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Biceps curl cable', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Biceps curl machine', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Ez bar biceps curl', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Rope cable curl', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Concentration curl', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Overhead cable curl', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Preacher curl dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Preacher curl barbell', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Preacher curl ez bar', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Preacher curl machine', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Preacher curl cable', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Seated incline curl dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Single arm cable curl', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Single arm behind the back cable curl', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Spider curl barbell', 1),
   (1, CURRENT_TIMESTAMP, 2, true, 'Spider curl dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Dip', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Dip assisted', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Seated dip machine', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Dip machine', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Dip weighted', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Bench dip', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Floor dip', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Ring dip', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Bench press close grip barbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Diamond push up', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Pike pushup', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Scullcrusher barbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Scullcrusher dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Single arm triceps extension', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Single arm triceps pushdown', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Behind the back single arm cable extension', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Standing triceps extension barbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Standing triceps extension dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Standing triceps extension cable', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Seated triceps extension barbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Seated triceps extension dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Seated triceps extension cable', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Triceps extension machine', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Triceps kickback cable', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Triceps kickback dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Triceps pushdown cable', 1),
   (1, CURRENT_TIMESTAMP, 3, true, 'Triceps pushdown rope', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Hammers', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Cross body hammer curl', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Standing barbell overhand grip curl', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Standing dumbbell overhand grip curl', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Standing cable overhand grip curl', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Wrist roller', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Seated wrist extension', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Behind the back wrist curl', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Palms up cable wrist curl', 1),
   (1, CURRENT_TIMESTAMP, 4, true, 'Palms up dumbbell wrist curl', 1),
   (1, CURRENT_TIMESTAMP, 5, true, 'Barbell shrugs', 1),
   (1, CURRENT_TIMESTAMP, 5, true, 'Dumbbell shrugs', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Pull up', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Pull up assisted', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Pull up weighted', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Wide pull up', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Lat pullover cable', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Lat pullover rope', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Lat pulldown', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Lat pulldown wide grip', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Lat pulldown v grip', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Lat pulldown machine', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Chin up', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Chin up assisted', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Chin up weighted', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Iso lateral row machine', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Iso lateral high row machine', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Iso lateral low row machine', 1),
   (1, CURRENT_TIMESTAMP, 6, true, 'Kneeling pulldown', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Bent over row barbell', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Bent over row dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Chest supported incline row dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Dead hang', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Inverted row', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Landmine row', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'One arm dumbbell row', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Rear delt reverse fly cable', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Rear delt reverse fly dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Rear delt reverse fly machine', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Seated cable row bar grip', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Seated cable row wide bar grip', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Seated cable row v grip', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Seated row machine', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'Single arm cable row', 1),
   (1, CURRENT_TIMESTAMP, 7, true, 'T bar row', 1),
   (1, CURRENT_TIMESTAMP, 8, true, 'Back extension', 1),
   (1, CURRENT_TIMESTAMP, 8, true, 'Back extension machine', 1),
   (1, CURRENT_TIMESTAMP, 8, true, 'Back extension weighted', 1),
   (1, CURRENT_TIMESTAMP, 8, true, 'Superman', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Cable crunch', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Standing cable crunch', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Hanging knee raise', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Ab scissors', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Ab wheel', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Bicycle crunch', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Cable twist', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Crunch', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Crunch weighted', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Dead bug', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Decline crunch', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Decline crunch weighted', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Dragon flag', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Elbow to knee', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Flutter kicks', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Front lever', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Hanging leg raise', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Heel traps', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Hollow body', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Jackknife sit up', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Knee raise parallel bars', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Leg raise parallel bars', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'L-sit', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Plank', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Russian twist', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Side bend', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Seated ab crunch machine', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Sit up', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'Toes to bar', 1),
   (1, CURRENT_TIMESTAMP, 9, true, 'V up', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Barbell squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Leg extension machine', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Leg press machine', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Bulgarian split squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Pistol squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Box squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Dumbbell step up', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Hack squat barbell', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Hack squat machine', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Jump squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Kettlebell squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Leg press horizontal machine', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Lunge', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Lunge barbell', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Lunge dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Pendulum squat machine', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Smith squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Step up', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Sumo squat', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Wall sit', 1),
   (1, CURRENT_TIMESTAMP, 10, true, 'Zercher squat', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'Barbell glute bridge', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'Barbell hip thrust', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'Hip thrust machine', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'Lateral band walks', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'Cable pull through', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'One legged cable kickback', 1),
   (1, CURRENT_TIMESTAMP, 11, true, 'Bridge butt lift', 1),
   (1, CURRENT_TIMESTAMP, 12, true, 'Hip abduction machine', 1),
   (1, CURRENT_TIMESTAMP, 12, true, 'Cable hip abduction', 1),
   (1, CURRENT_TIMESTAMP, 12, true, 'Seated resistance band abduction', 1),
   (1, CURRENT_TIMESTAMP, 13, true, 'Hip adduction machine', 1),
   (1, CURRENT_TIMESTAMP, 13, true, 'Cable hip adduction', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Romanian deadlift', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Seated leg curl', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Lying leg curl', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Good morning', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Standing leg curl', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Glute ham rise', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Single leg Romanian deadlift barbell', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Single leg Romanian deadlift dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Nordic hamstrings curls', 1),
   (1, CURRENT_TIMESTAMP, 14, true, 'Straight leg deadlift', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Calf extension machine', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Calf press machine', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Seated calf raise machine', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Seated calf raise dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Single leg standing calf raise', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Standing calf raise barbell', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Standing calf raise dumbbell', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Standing calf raise machine', 1),
   (1, CURRENT_TIMESTAMP, 15, true, 'Standing calf raise smith', 1);


